### ISSUE TITLE
Wrong link for the Revisiting Document Image Dewarping by Grid Regularization paper

### ISSUE THREAD

**Issue by tanguymagne** [fh2019ustc/Awesome-Document-Image-Rectification#1]
The link in the Result column for the Revisiting Document Image Dewarping by Grid Regularization redirects to the WarpDoc dataset, which was published with the Fourier Document Restoration for Robust Document Dewarping and Recognition paper.

Do you know if the results of this paper are actually available?

**Comment by fh2019ustc** [comment]
I obtain the results of Revisiting Document Image Dewarping by Grid Regularization from the authors. I release their results after their permission.

**Comment by tanguymagne** [comment]
I saw you fixed the link. Thank you!
