### ISSUE TITLE
无法下载DocUNet Benchmark数据...提示403Forbidden

### ISSUE THREAD

**Issue by yazheng0307** [fh2019ustc/Awesome-Document-Image-Rectification#2]
进入这个网页https://www3.cs.stonybrook.edu/~cvl/docunet.html下载的时候就提示403Forbidden,题主知道为什么吗

![ee3f28d6a95acd96a268becbb4d11e7](https://user-images.githubusercontent.com/50820616/210043210-1f571f1a-3a9a-46e7-8d4f-207cc5cdb600.png)

![image](https://user-images.githubusercontent.com/50820616/210043071-66b79056-b5c7-4e81-9726-798c3210ce48.png)

**Comment by fh2019ustc** [comment]
据我了解，这个可能和他们这台服务器暂时关闭有关。如果你需要，我可以share给你我之前下载的。
